# Generated by Django 4.2.30 on 2026-09-26 09:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('name', models.CharField(help_text='Product name (e.g. Kubbus, Romali)', max_length=100, unique=True)),
                ('code', models.CharField(help_text='Product SKU or identifier (e.g. KUB, ROM)', max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Standard unit selling price in INR (e.g. 35.00)', max_digits=12)),
                ('packet_size', models.CharField(blank=True, help_text='Packaging specification (e.g. 10 pcs / pack)', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
    ]
