# Generated by Django 4.2.30 on 2026-10-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order_number', 'created_at', 'name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='order_number',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Display/sequence order number (e.g. 1 for Kubbus, 2 for Bun, 3 for Romali)'),
        ),
    ]
