# Generated by Django 4.2.30 on 2026-10-05 08:43

from django.db import migrations, models


def set_default_skip_for_bun(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    Product.objects.filter(models.Q(name__icontains='bun') | models.Q(code__icontains='bun')).update(skip_in_entry=True)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_product_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='skip_in_entry',
            field=models.BooleanField(default=False, help_text='Skip this product column during fast Enter key order entry'),
        ),
        migrations.RunPython(set_default_skip_for_bun, reverse_code=migrations.RunPython.noop),
    ]
