# Generated by Django 4.2.30 on 2026-09-26 18:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shop_expense',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Shop expense, damages, or returns deducted from order total', max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='shop_expense_notes',
            field=models.CharField(blank=True, help_text='Remarks/reason for shop expense', max_length=255),
        ),
    ]
