# Generated by Django 4.2.30 on 2026-09-26 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0003_order_shop_expense_order_shop_expense_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='entered_by_name',
            field=models.CharField(blank=True, help_text='Name of the person who entered the order (e.g., Customer Name)', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='entered_by_role',
            field=models.CharField(blank=True, help_text='Role of the person who entered the order', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='entered_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(default='MANAGER', help_text='Source of the order: CUSTOMER_LINK, MANAGER, OWNER', max_length=50),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='entered_by_type',
            field=models.CharField(blank=True, help_text='CUSTOMER, MANAGER, OWNER', max_length=50),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='entered_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_order_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMATION_PENDING', 'Confirmation Pending'), ('SUBMITTED', 'Submitted'), ('LOCKED', 'Locked'), ('BILLING', 'Billing'), ('DELIVERY_CREATED', 'Delivery Created'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='OrderActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('action', models.CharField(max_length=255)),
                ('user_name', models.CharField(blank=True, max_length=100)),
                ('user_role', models.CharField(blank=True, max_length=50)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Activity Log',
                'verbose_name_plural': 'Order Activity Logs',
                'ordering': ['created_at'],
            },
        ),
    ]
