# Generated by Django 4.2.30 on 2026-09-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_entered_by_name_order_entered_by_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMATION_PENDING', 'Confirmation Pending'), ('SUBMITTED', 'Submitted'), ('LOCKED', 'Locked'), ('BILLING', 'Billing'), ('DELIVERY_CREATED', 'Delivery Created'), ('DELIVERED', 'Delivered'), ('NOT_DELIVERED', 'Not Delivered'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20),
        ),
    ]
