# Generated by Django 4.2.30 on 2026-09-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('orders', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='submitted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when order was submitted', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('CONFIRMATION_PENDING', 'Confirmation Pending'), ('CONFIRMED', 'Confirmed'), ('SUBMITTED', 'Submitted'), ('LOCKED', 'Locked'), ('BILLING', 'Billing'), ('DELIVERY_CREATED', 'Delivery Created'), ('DELIVERED', 'Delivered'), ('NOT_DELIVERED', 'Not Delivered'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'product')},
        ),
    ]
