# Generated by Django 4.2.30 on 2026-09-26 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('transaction_type', models.CharField(choices=[('OPENING_BALANCE', 'Opening Balance'), ('CREDIT_SALE', 'Credit Sale'), ('CASH_PAYMENT', 'Cash Payment'), ('GPAY_PAYMENT', 'GPay / UPI Payment'), ('ADJUSTMENT', 'Authorized Adjustment')], db_index=True, max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction delta in INR (+ increases receivable, - decreases receivable)', max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text="Snapshot of the customer's balance immediately after this transaction", max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(help_text='Customer shop account', on_delete=django.db.models.deletion.PROTECT, related_name='credit_transactions', to='customers.customer')),
                ('recorded_by', models.ForeignKey(help_text='User who triggered or authorized this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_credit_transactions', to=settings.AUTH_USER_MODEL)),
                ('reference_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_ledger_entries', to='orders.order')),
                ('reference_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_ledger_entries', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Credit Ledger Entry',
                'verbose_name_plural': 'Credit Ledger Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
