# Generated by Django 4.2.30 on 2026-09-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransaction',
            name='transaction_type',
            field=models.CharField(choices=[('OPENING_BALANCE', 'Opening Balance'), ('CREDIT_SALE', 'Credit Sale'), ('CASH_PAYMENT', 'Cash Payment'), ('GPAY_PAYMENT', 'GPay / UPI Payment'), ('ORDER_PAYMENT', 'Order Payment'), ('PREVIOUS_CREDIT_PAYMENT', 'Previous Credit Payment'), ('ADJUSTMENT', 'Authorized Adjustment'), ('PAYMENT_REVERSAL', 'Payment Reversal / Void')], db_index=True, max_length=30),
        ),
    ]
