# Generated by Antigravity to backfill historical unposted credit sales
from decimal import Decimal
from django.db import migrations


def reconcile_orders_and_balances(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    Customer = apps.get_model('customers', 'Customer')
    CreditTransaction = apps.get_model('credits', 'CreditTransaction')

    # Select all valid positive orders in chronological order
    orders = (
        Order.objects.exclude(status='CANCELLED')
        .filter(total_amount__gt=0)
        .order_by('order_date', 'created_at')
    )

    for ord_obj in orders:
        # Check if CREDIT_SALE already exists for this order
        has_tx = CreditTransaction.objects.filter(
            reference_order=ord_obj,
            transaction_type='CREDIT_SALE'
        ).exists()

        if not has_tx:
            try:
                cust = Customer.objects.get(id=ord_obj.customer_id)
            except Customer.DoesNotExist:
                continue

            order_amount = ord_obj.total_amount
            new_balance = (cust.current_balance + order_amount).quantize(Decimal('0.01'))
            cust.current_balance = new_balance
            cust.save(update_fields=['current_balance'])

            tx = CreditTransaction.objects.create(
                customer=cust,
                transaction_type='CREDIT_SALE',
                amount=order_amount,
                balance_after=new_balance,
                reference_order=ord_obj,
                notes=f"Reconciled credit sale for order #{ord_obj.order_number}",
            )
            # Update created_at to match original order created_at (bypassing auto_now_add)
            if ord_obj.created_at:
                CreditTransaction.objects.filter(id=tx.id).update(created_at=ord_obj.created_at)


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('credits', '0002_alter_credittransaction_transaction_type'),
        ('orders', '0006_order_submitted_at_alter_order_status_and_more'),
        ('customers', '0003_customerdocument'),
    ]

    operations = [
        migrations.RunPython(reconcile_orders_and_balances, reverse_code=migrations.RunPython.noop),
    ]
