# Generated by Django 4.2.30 on 2026-09-26 09:02

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('name', models.CharField(help_text='Shop or establishment name', max_length=150)),
                ('owner_name', models.CharField(blank=True, help_text='Proprietor / store manager name', max_length=100)),
                ('phone', models.CharField(help_text='Primary contact phone number', max_length=20)),
                ('alternative_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(help_text='Street address / location')),
                ('landmark', models.CharField(blank=True, help_text='Nearby landmark for delivery drivers', max_length=100)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('5000.00'), help_text='Maximum allowed outstanding credit', max_digits=12)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current outstanding balance owed by customer (receivable)', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('route', models.ForeignKey(help_text='Designated delivery route for this customer', on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='routes.route')),
            ],
            options={
                'verbose_name': 'Customer Shop',
                'verbose_name_plural': 'Customer Shops',
                'ordering': ['route__name', 'name'],
            },
        ),
    ]
