# Generated by Django 4.2.30 on 2026-09-26 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes about shop or delivery preferences'),
        ),
        migrations.CreateModel(
            name='CustomerProductPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('price', models.DecimalField(decimal_places=2, help_text='Negotiated selling price in INR (always Decimal)', max_digits=12)),
                ('effective_from', models.DateField(default=django.utils.timezone.now, help_text='Date from which this price becomes active')),
                ('effective_to', models.DateField(blank=True, help_text='Optional expiry date for temporary promo pricing', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this custom price is currently in effect')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customer_prices', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Customer shop receiving this negotiated price', on_delete=django.db.models.deletion.CASCADE, related_name='custom_prices', to='customers.customer')),
                ('product', models.ForeignKey(help_text='Bakery product', on_delete=django.db.models.deletion.CASCADE, related_name='customer_prices', to='products.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_customer_prices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Product Price',
                'verbose_name_plural': 'Customer Product Prices',
                'ordering': ['customer__name', 'product__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='customerproductprice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('customer', 'product'), name='unique_active_customer_product_price'),
        ),
    ]
