# Generated by Django 4.2.30 on 2026-10-05 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0002_customer_notes_customerproductprice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('title', models.CharField(help_text='Title or name of document', max_length=200)),
                ('document_type', models.CharField(choices=[('FSSAI_LICENSE', 'FSSAI Food License'), ('GST_CERTIFICATE', 'GST Certificate'), ('TRADE_LICENSE', 'Trade / Municipal License'), ('RENT_AGREEMENT', 'Rent / Lease Agreement'), ('ID_PROOF', 'Owner / Manager ID Proof'), ('SHOP_PHOTO', 'Shop Front / Location Photo'), ('BANK_PROOF', 'Bank Cheque / Passbook'), ('CONTRACT', 'Wholesale Supply Contract'), ('OTHER', 'Other Document')], default='OTHER', help_text='Category of the document', max_length=40)),
                ('file', models.FileField(help_text='Uploaded document file (PDF, image, doc, etc.)', upload_to='customer_documents/%Y/%m/')),
                ('file_name', models.CharField(blank=True, help_text='Original file name', max_length=255)),
                ('file_size', models.BigIntegerField(default=0, help_text='File size in bytes')),
                ('mime_type', models.CharField(blank=True, help_text='MIME type', max_length=100)),
                ('document_number', models.CharField(blank=True, help_text='Optional document or registration number', max_length=100)),
                ('expiry_date', models.DateField(blank=True, help_text='Optional expiry date for licenses/agreements', null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes or description')),
                ('customer', models.ForeignKey(help_text='Customer shop this document belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='customers.customer')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_customer_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Document',
                'verbose_name_plural': 'Customer Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
