# Generated by Django 4.2.30 on 2026-10-04 16:56

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_devicesession'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('full_name', models.CharField(help_text='Full Name of staff member', max_length=150)),
                ('phone_number', models.CharField(blank=True, help_text='Contact telephone/mobile number', max_length=20)),
                ('designation', models.CharField(default='Worker', help_text='Role/Designation e.g. Bakery Worker, Helper, Cleaner, Delivery, Counter', max_length=100)),
                ('joined_date', models.DateField(default=django.utils.timezone.localdate, help_text='Date when staff member joined Zamzam Foods')),
                ('wage_type', models.CharField(choices=[('DEFAULT_SLAB', 'Tenure Based Slab (₹400/₹500/₹600)'), ('CUSTOM', 'Custom Daily Amount')], default='DEFAULT_SLAB', help_text='Default slab calculation or custom fixed wage', max_length=20)),
                ('custom_daily_wage', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Custom daily wage if WageType is CUSTOM', max_digits=10, null=True)),
                ('proof_document', models.FileField(blank=True, help_text='Identity document / photo / PDF (Aadhaar, ID proof)', null=True, upload_to='staff_proofs/')),
                ('is_active', models.BooleanField(default=True, help_text='Active employment status')),
                ('notes', models.TextField(blank=True, help_text='Address, remarks, emergency contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_staff_profiles', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, help_text='Optional linked login user (if staff has login access)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_member_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Member',
                'verbose_name_plural': 'Staff Members',
                'ordering': ['full_name', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffPayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount paid in INR', max_digits=10)),
                ('payout_type', models.CharField(choices=[('SALARY', 'Salary / Wage Payout'), ('ADVANCE', 'Cash Advance'), ('BONUS', 'Bonus / Incentive'), ('OTHER', 'Other')], default='SALARY', max_length=30)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('GPAY_UPI', 'GPay / UPI')], default='CASH', max_length=20)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('reference', models.CharField(blank=True, help_text='Bill / receipt / UPI transaction ref', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Remarks, e.g. weekly salary, advance for travel')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_staff_payouts', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='accounts.staffmember')),
            ],
            options={
                'verbose_name': 'Staff Payout',
                'verbose_name_plural': 'Staff Payouts',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('FULL', 'Full Day'), ('HALF', 'Half Day'), ('LEAVE', 'Leave / Absent')], db_index=True, default='FULL', max_length=20)),
                ('daily_wage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated wage for this attendance record', max_digits=10)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_staff_attendances', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='accounts.staffmember')),
            ],
            options={
                'verbose_name': 'Staff Attendance',
                'verbose_name_plural': 'Staff Attendances',
                'ordering': ['-date', 'staff__full_name'],
                'unique_together': {('staff', 'date')},
            },
        ),
    ]
