# Generated by Django 4.2.30 on 2026-10-05 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_staffmember_role_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='designation',
            field=models.CharField(default='Share Member', help_text='Role/Designation e.g. Share Member, Business Partner, Staff Driver, Sales / Counter', max_length=100),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='role_type',
            field=models.CharField(choices=[('STAFF', 'Staff (Driver / Operations)'), ('MEMBER', 'Share Member (Business Owner / Partner)')], db_index=True, default='MEMBER', help_text='Role classification: STAFF (Driver / Management / Operations) or MEMBER (Business Owner / Share Member)', max_length=20),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='wage_type',
            field=models.CharField(choices=[('DEFAULT_SLAB', 'Automatic Tenure Slabs (₹400/₹500/₹600/₹700/₹800)'), ('CUSTOM', 'Custom Daily Amount')], default='DEFAULT_SLAB', help_text='Default slab calculation or custom fixed wage', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('DRIVER', 'Staff Driver')], db_index=True, default='DRIVER', help_text='Designated role within the company', max_length=20),
        ),
    ]
