# Generated by Django 4.2.30 on 2026-09-27 07:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_customer_notes_customerproductprice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('shop', models.CharField(db_index=True, default='default', help_text='Tenant / Shop identifier', max_length=100)),
                ('waba_id', models.CharField(blank=True, db_index=True, help_text='Meta WhatsApp Business Account ID', max_length=100)),
                ('phone_number_id', models.CharField(db_index=True, help_text='Meta WhatsApp Phone Number ID (used in webhooks and Cloud API)', max_length=100, unique=True)),
                ('business_phone', models.CharField(blank=True, help_text='Sender / Business display phone number', max_length=30)),
                ('status', models.CharField(default='active', help_text='Account connection status', max_length=30)),
            ],
            options={
                'verbose_name': 'WhatsApp Account',
                'verbose_name_plural': 'WhatsApp Accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('shop', models.CharField(db_index=True, default='default', help_text='Tenant / Shop identifier', max_length=100)),
                ('whatsapp_phone', models.CharField(db_index=True, help_text='Customer phone number', max_length=30)),
                ('last_message', models.TextField(blank=True, help_text='Snippet of the latest message')),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp of latest message', null=True)),
                ('unread_count', models.IntegerField(default=0, help_text='Count of unread incoming messages')),
                ('customer', models.ForeignKey(blank=True, help_text='Associated Zamzam Customer Shop', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_conversations', to='customers.customer')),
            ],
            options={
                'verbose_name': 'WhatsApp Conversation',
                'verbose_name_plural': 'WhatsApp Conversations',
                'ordering': ['-last_message_at', '-created_at'],
                'unique_together': {('shop', 'whatsapp_phone')},
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('whatsapp_message_id', models.CharField(db_index=True, help_text='Unique Meta WhatsApp Message ID (wamid)', max_length=150, unique=True)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], db_index=True, default='inbound', max_length=15)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('document', 'Document'), ('audio', 'Audio'), ('voice', 'Voice'), ('video', 'Video'), ('other', 'Other')], default='text', max_length=20)),
                ('text', models.TextField(blank=True, help_text='Text content or media caption')),
                ('media_id', models.CharField(blank=True, help_text='Meta media ID for images/documents/audio', max_length=150)),
                ('media_url', models.URLField(blank=True, help_text='Accessible media URL if cached', max_length=500)),
                ('timestamp', models.DateTimeField(db_index=True, help_text='Timestamp delivered by WhatsApp Cloud API')),
                ('raw_payload', models.JSONField(blank=True, help_text='Full raw webhook message JSON payload', null=True)),
                ('conversation', models.ForeignKey(help_text='Conversation thread this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp.whatsappconversation')),
            ],
            options={
                'verbose_name': 'WhatsApp Message',
                'verbose_name_plural': 'WhatsApp Messages',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppCustomer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('shop', models.CharField(db_index=True, default='default', help_text='Tenant / Shop identifier', max_length=100)),
                ('whatsapp_phone', models.CharField(db_index=True, help_text='Standardized WhatsApp phone number (e.g. 919876543210)', max_length=30)),
                ('name', models.CharField(blank=True, help_text='Customer / Shop name', max_length=150)),
                ('profile_name', models.CharField(blank=True, help_text='Meta WhatsApp profile push name', max_length=150)),
                ('customer', models.ForeignKey(blank=True, help_text='Associated Zamzam Customer Shop', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_profiles', to='customers.customer')),
            ],
            options={
                'verbose_name': 'WhatsApp Customer',
                'verbose_name_plural': 'WhatsApp Customers',
                'ordering': ['-created_at'],
                'unique_together': {('shop', 'whatsapp_phone')},
            },
        ),
    ]
