# Generated by Django 4.2.30 on 2026-09-26 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('name', models.CharField(help_text='Route name (e.g. Pandikkad)', max_length=100, unique=True)),
                ('code', models.CharField(help_text='Short route code (e.g. PKD)', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Geographical or delivery notes')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Delivery Route',
                'verbose_name_plural': 'Delivery Routes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('vehicle_number', models.CharField(blank=True, help_text='Vehicle registration number', max_length=30)),
                ('license_number', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_route', models.ForeignKey(blank=True, help_text='Primary territory/route assigned to this driver', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='routes.route')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Driver Profile',
                'verbose_name_plural': 'Driver Profiles',
                'ordering': ['user__first_name', 'user__username'],
            },
        ),
    ]
