# Generated by Django 4.2.30 on 2026-09-26 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('category', models.CharField(choices=[('PETROL_FUEL', 'Petrol / Fuel'), ('FOOD', 'Food'), ('PARKING', 'Parking'), ('TOLL', 'Toll'), ('VEHICLE_REPAIR', 'Vehicle Expense'), ('OTHER', 'Other')], db_index=True, default='PETROL_FUEL', help_text='Expense classification', max_length=50)),
                ('custom_category', models.CharField(blank=True, help_text="Custom category description if 'Other' selected", max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Expense amount in INR (always Decimal)', max_digits=12)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now, help_text='Date on which expense occurred')),
                ('notes', models.TextField(blank=True, help_text='Remarks, vendor name, or invoice notes')),
                ('receipt_reference', models.CharField(blank=True, help_text='Bill / receipt number', max_length=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_driver_expenses', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(help_text='Driver who incurred this expense', on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='routes.driver')),
            ],
            options={
                'verbose_name': 'Driver Expense',
                'verbose_name_plural': 'Driver Expenses',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
