# Generated by Django 4.2.30 on 2026-09-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_driverexpense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverexpense',
            name='category',
            field=models.CharField(choices=[('PETROL_FUEL', 'Petrol / Fuel'), ('PETROL', 'Petrol'), ('FOOD', 'Food'), ('PARKING', 'Parking'), ('TOLL', 'Toll'), ('MAINTENANCE', 'Vehicle Maintenance'), ('VEHICLE_REPAIR', 'Vehicle Expense'), ('OTHER', 'Other')], db_index=True, default='PETROL_FUEL', help_text='Expense classification', max_length=50),
        ),
    ]
