# Generated by Django 4.2.30 on 2026-09-26 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_alter_driverexpense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverexpense',
            name='category',
            field=models.CharField(choices=[('PETROL_FUEL', 'Petrol / Fuel'), ('PETROL', 'Petrol'), ('FOOD', 'Food'), ('PARKING', 'Parking'), ('TOLL', 'Toll'), ('MAINTENANCE', 'Vehicle Maintenance'), ('VEHICLE_REPAIR', 'Vehicle Expense'), ('SHOP_EXPENSE', 'Shop Expense'), ('OTHER', 'Other')], db_index=True, default='PETROL_FUEL', help_text='Expense classification', max_length=50),
        ),
        migrations.AlterField(
            model_name='driverexpense',
            name='driver',
            field=models.ForeignKey(blank=True, help_text='Driver who incurred this expense (optional for shop or general expenses)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='routes.driver'),
        ),
    ]
