# Generated by Django 4.2.30 on 2026-09-26 18:48

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_alter_driverexpense_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverexpense',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate, help_text='Date on which expense occurred'),
        ),
        migrations.CreateModel(
            name='DriverShift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate, help_text='Shift date')),
                ('is_opened', models.BooleanField(default=False)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('kubbus_loaded', models.IntegerField(default=0, help_text='Total Kubbus pieces (ps) taken at start')),
                ('romali_loaded', models.IntegerField(default=0, help_text='Total Romali pieces (ps) taken at start')),
                ('opening_notes', models.TextField(blank=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('kubbus_returned', models.IntegerField(default=0, help_text='Unsold Kubbus pieces returned')),
                ('romali_returned', models.IntegerField(default=0, help_text='Unsold Romali pieces returned')),
                ('cash_collected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('upi_collected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('expenses_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_cash_handover', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('closing_notes', models.TextField(blank=True)),
                ('driver', models.ForeignKey(help_text='Driver running this shift', on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='routes.driver')),
            ],
            options={
                'verbose_name': 'Driver Shift',
                'verbose_name_plural': 'Driver Shifts',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('driver', 'date')},
            },
        ),
    ]
