# Generated by Django 4.2.30 on 2026-10-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_alter_driverexpense_date_drivershift'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driverexpense',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Expense', 'verbose_name_plural': 'Expenses'},
        ),
        migrations.AlterField(
            model_name='driverexpense',
            name='category',
            field=models.CharField(choices=[('SHOP_EXPENSE', 'Shop Expense'), ('MAINTENANCE', 'Shop & Vehicle Maintenance'), ('RAW_MATERIAL', 'Raw Materials / Packaging'), ('PETROL_FUEL', 'Petrol / Fuel'), ('PETROL', 'Petrol'), ('FOOD', 'Food / Meals'), ('PARKING', 'Parking'), ('TOLL', 'Toll'), ('UTILITY', 'Electricity / Rent / Utilities'), ('SALARY_WAGES', 'Daily Wages / Allowance'), ('VEHICLE_REPAIR', 'Vehicle Expense'), ('OTHER', 'Other')], db_index=True, default='SHOP_EXPENSE', help_text='Expense classification', max_length=50),
        ),
    ]
