# Generated by Django 4.2.30 on 2026-09-26 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('payment_number', models.CharField(db_index=True, help_text='Unique receipt identifier (e.g. PAY-20260926-0001)', max_length=30, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount in INR (always Decimal)', max_digits=12)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('GPAY_UPI', 'GPay / UPI')], db_index=True, default='CASH', max_length=20)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('REVERSED', 'Reversed')], db_index=True, default='COMPLETED', max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='UPI Reference ID / Transaction Ref / Receipt Ref', max_length=100)),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Exact timestamp payment was received')),
                ('notes', models.TextField(blank=True)),
                ('collected_by', models.ForeignKey(help_text='Staff member (driver/manager) who received the funds', on_delete=django.db.models.deletion.PROTECT, related_name='collected_payments', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Customer making the payment', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='customers.customer')),
                ('order', models.ForeignKey(blank=True, help_text='Associated order if collected specifically for an order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='orders.order')),
            ],
            options={
                'verbose_name': 'Payment Record',
                'verbose_name_plural': 'Payment Records',
                'ordering': ['-received_at', '-created_at'],
            },
        ),
    ]
