# Generated by Django 4.2.30 on 2026-10-05 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_staffmember_designation_and_more'),
        ('payments', '0002_payment_reversal_reason_payment_reversed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='staff_member',
            field=models.ForeignKey(blank=True, help_text='Staff or Share Member who physically received the money from the shop', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_payments', to='accounts.staffmember'),
        ),
    ]
