# Generated by Django 4.2.30 on 2026-09-26 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=150)),
                ('user_role', models.CharField(blank=True, max_length=50)),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('DELETED', 'Deleted'), ('STATUS_CHANGED', 'Status Changed'), ('PRICE_OVERRIDE', 'Price Overridden'), ('DELIVERED', 'Delivered'), ('NOT_DELIVERED', 'Not Delivered'), ('CANCELLED', 'Cancelled')], db_index=True, max_length=50)),
                ('entity_type', models.CharField(choices=[('ORDER', 'Order'), ('PRICE', 'Customer Price'), ('PAYMENT', 'Payment'), ('DELIVERY', 'Delivery'), ('EXPENSE', 'Driver Expense'), ('CUSTOMER', 'Customer'), ('PRODUCT', 'Product')], db_index=True, max_length=50)),
                ('entity_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('entity_name', models.CharField(blank=True, max_length=255)),
                ('summary', models.TextField(help_text='Human readable summary of the event')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Structured old/new values and metadata')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='common_acti_entity__723bc4_idx'), models.Index(fields=['timestamp', 'action'], name='common_acti_timesta_217eb4_idx')],
            },
        ),
    ]
