# Generated by Django 4.2.30 on 2026-09-27 09:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('business_name', models.CharField(default='Zamzam Foods Wholesale', help_text='Official business/shop name displayed on bills and invoices', max_length=200)),
                ('phone_number', models.CharField(default='+91 98470 12345', help_text='Official business phone number', max_length=50)),
                ('gst_number', models.CharField(blank=True, default='', help_text='GSTIN / Tax Identification Number', max_length=50)),
                ('email', models.EmailField(blank=True, default='info@zamzamfoods.com', help_text='Business contact email', max_length=254)),
                ('address', models.TextField(blank=True, default='Main Road, Pandikkad, Malappuram, Kerala', help_text='Physical address of business / bakery facility')),
                ('upi_id', models.CharField(blank=True, default='', help_text='UPI ID (VPA) for digital customer payments (e.g. zamzam@okaxis)', max_length=100)),
                ('invoice_footer_notes', models.TextField(blank=True, default='Thank you for your business. Fresh Kubbus & Romali rotis delivered daily.', help_text='Footer remarks printed on bills and share messages')),
                ('is_whatsapp_enabled', models.BooleanField(default=True, help_text='Master toggle to enable or disable WhatsApp sharing options across the entire system')),
                ('is_self_order_enabled', models.BooleanField(default=True, help_text='Master toggle to enable or disable customer online self-ordering via public link')),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
