# Generated by Django 4.2.30 on 2026-09-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='is_maintenance_mode',
            field=models.BooleanField(default=False, help_text='Master toggle to put system under maintenance. When ON, only Admin/Owner can access.'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='maintenance_message',
            field=models.TextField(blank=True, default='System is currently undergoing scheduled maintenance. Please check back shortly.', help_text='Custom message displayed to staff and customers while maintenance mode is active'),
        ),
    ]
