# Generated by Django 4.2.30 on 2026-09-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_systemsettings_is_maintenance_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='whatsapp_is_locked',
            field=models.BooleanField(default=False, help_text='Lock status for WhatsApp feature. If True, requires upgrade key to unlock.'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='whatsapp_license_key',
            field=models.CharField(blank=True, default='', help_text='Active license/upgrade key used to unlock or extend the plan', max_length=100),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='whatsapp_plan_expires_at',
            field=models.DateTimeField(blank=True, help_text='Expiration timestamp for WhatsApp plan. If expired, feature locks.', null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='whatsapp_plan_name',
            field=models.CharField(blank=True, default='WhatsApp Enterprise Pro', help_text='Active plan name (e.g. Free Trial, Pro 30-Day, Annual License, Lifetime)', max_length=100),
        ),
    ]
