# Generated by Django 4.2.30 on 2026-10-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_systemsettings_whatsapp_is_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='is_order_discount_enabled',
            field=models.BooleanField(default=True, help_text="Master toggle to show or hide the 'Disc (₹)' column in Fast Wholesale Order Entry"),
        ),
    ]
