# Generated by Django 4.2.30 on 2026-10-05 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_systemsettings_is_order_discount_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='is_driver_module_enabled',
            field=models.BooleanField(default=True, help_text='Master toggle to enable or disable the entire Delivery Driver portion, driver mobile portal, routes driver dispatch, and driver performance tracking across the system'),
        ),
    ]
