# Generated by Django 4.2.30 on 2026-10-05 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_systemsettings_is_driver_module_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='settings_pin_code',
            field=models.CharField(blank=True, default='7667', help_text='4-digit security PIN to access Business Settings & System Controls (Default: 7667)', max_length=10),
        ),
    ]
