# Generated by Django 4.2.30 on 2026-10-05 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0007_systemsettings_settings_pin_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('title', models.CharField(help_text='Title or name of the document', max_length=200)),
                ('document_type', models.CharField(choices=[('FSSAI_LICENSE', 'FSSAI Food Safety License'), ('GST_CERTIFICATE', 'GST Registration Certificate'), ('TRADE_LICENSE', 'Trade / Municipal License'), ('SHOP_ACT', 'Shop & Establishment Act'), ('FIRE_NOC', 'Fire NOC / Safety Certificate'), ('POLLUTION_NOC', 'Pollution Control NOC'), ('BANK_DOCUMENT', 'Bank Account / Cheque'), ('INSURANCE', 'Business Insurance Policy'), ('RENT_AGREEMENT', 'Rent / Lease Agreement'), ('PAN_CARD', 'PAN Card'), ('UDYAM', 'Udyam / MSME Registration'), ('HALAL_CERT', 'Halal Certification'), ('QUALITY_CERT', 'Quality / ISO Certification'), ('OTHER', 'Other Document')], db_index=True, default='OTHER', max_length=40)),
                ('file', models.FileField(help_text='Uploaded document file (PDF, image, etc.)', upload_to='business_documents/%Y/%m/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.BigIntegerField(default=0, help_text='File size in bytes')),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('document_number', models.CharField(blank=True, help_text='License / registration number (e.g. FSSAI 13325999000000)', max_length=150)),
                ('issuing_authority', models.CharField(blank=True, help_text='Issuing body or government authority', max_length=200)),
                ('issue_date', models.DateField(blank=True, help_text='Date of issue', null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='Expiry / renewal date', null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Mark document as active/inactive')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_business_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business Document',
                'verbose_name_plural': 'Business Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
