# Generated by Django 4.2.30 on 2026-09-26 09:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('delivery_number', models.CharField(db_index=True, help_text='Unique delivery dispatch code (e.g. DEL-20260926-0001)', max_length=30, unique=True)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('RETURNED', 'Returned')], db_index=True, default='ASSIGNED', max_length=20)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_name', models.CharField(blank=True, help_text='Shop staff who acknowledged delivery', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Delivery confirmation remarks')),
                ('driver', models.ForeignKey(help_text='Assigned delivery driver', on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='routes.driver')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='orders.order')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='routes.route')),
            ],
            options={
                'verbose_name': 'Delivery Dispatch',
                'verbose_name_plural': 'Delivery Dispatches',
                'ordering': ['-created_at'],
            },
        ),
    ]
