# Generated by Django 4.2.30 on 2026-09-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='failed_reason',
            field=models.CharField(blank=True, help_text='Reason if shop was closed or refused', max_length=255),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('NOT_DELIVERED', 'Not Delivered'), ('FAILED', 'Failed'), ('RETURNED', 'Returned')], db_index=True, default='ASSIGNED', max_length=20),
        ),
    ]
