# Generated by Django 4.2.30 on 2026-09-26 10:13

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyClosing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('date', models.DateField(db_index=True, help_text='The calendar date being closed', unique=True)),
                ('is_closed', models.BooleanField(default=True, help_text='True if closed, False if reopened')),
                ('closed_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when closing was confirmed')),
                ('reopened_at', models.DateTimeField(blank=True, help_text='Timestamp when day was reopened', null=True)),
                ('reopen_reason', models.TextField(blank=True, help_text="Owner's mandatory explanation for reopening")),
                ('total_orders', models.IntegerField(default=0)),
                ('total_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_collected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('cash_collected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('upi_collected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('credit_generated', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('previous_credit_collected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('driver_expenses', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_collection', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('closed_by', models.ForeignKey(help_text='Manager or Owner who submitted the daily closing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_days', to=settings.AUTH_USER_MODEL)),
                ('reopened_by', models.ForeignKey(blank=True, help_text='Owner who reopened the closed day', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reopened_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Closing',
                'verbose_name_plural': 'Daily Closings',
                'ordering': ['-date'],
            },
        ),
    ]
