# Generated by Django 4.2.30 on 2026-09-26 17:59

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyclosing',
            name='is_opened',
            field=models.BooleanField(default=False, help_text='True if day was formally opened'),
        ),
        migrations.AddField(
            model_name='dailyclosing',
            name='opened_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when day was opened', null=True),
        ),
        migrations.AddField(
            model_name='dailyclosing',
            name='opened_by',
            field=models.ForeignKey(blank=True, help_text='Manager or Owner who opened the day', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_days', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyclosing',
            name='opening_cash',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Opening cash float in register at start of day', max_digits=12),
        ),
        migrations.AddField(
            model_name='dailyclosing',
            name='opening_notes',
            field=models.TextField(blank=True, help_text='Notes recorded during day opening'),
        ),
        migrations.AlterField(
            model_name='dailyclosing',
            name='closed_by',
            field=models.ForeignKey(blank=True, help_text='Manager or Owner who submitted the daily closing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_days', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dailyclosing',
            name='is_closed',
            field=models.BooleanField(default=True, help_text='True if closed, False if reopened or in progress'),
        ),
    ]
